### ISSUE TITLE
Complete and Sign-Off Team Charter

### ISSUE THREAD

**Issue by dzakich** [DLWM-MSE/CPSC-544#1]
We need to carefully and thoughtfully complete all sections of the Team Charted document, review it, assign roles, and submit

**Comment by dzakich** [comment]
Updated Team Member Skill Inventory within the **Team Charter** 👍

**Comment by jlarceo40** [comment]
Here is the email that I drafted to send to the professor for approval:

Title: CPSC 544 - Arceo, Legedza, Pak, SWE (ALPS) Team

Eric Pak, Stanislav Legedza, and I have decided to group together. In addition, we have decided to choose Python as our programming environment due to the unanimous desire to learn the language over Android. Please let us know if we are approved for the programming environment change.

Regards,

Jonathan Arceo

As always, let me know what you guys think.

**Comment by bengk** [comment]
What about changing Android to Java? You can still program Android in different languages.

**Comment by dzakich** [comment]
@DLWM-MSE/alps Excellent email, Jonny. Only one minor correction is in the Title: change from SWE to SwE 😃 
Otherwise, ship it.

**Comment by dzakich** [comment]
@bengk I think Jonny meant Android as programming environment and not as a distinct language

**Comment by dzakich** [comment]
@DLWM-MSE/alps But reading the body again, I perhaps see the confusion : Python is programming language (not environment as Jonny states), but Android is more of an environment (not a language)

**Comment by bengk** [comment]
Good point. Misread that part. Carry on.

**Comment by jlarceo40** [comment]
Technically, we can say that we are developing in the Python Environment; we will be developing an application written in Python. I believe when they say Android environment, they mean development of Android applications, while development in Java or C++ environment means developing applications in the respective languages. I say it is okay to say Python environment because we are using its syntax, functions, standard libraries, and etc.  

Either way, we can change the email to say the following:

Title: CPSC 544 - Arceo, Legedza, Pak, **SwE** (ALPS) Team

Eric Pak, Stanislav Legedza, and I have decided to group together. In addition, we have decided to choose Python as our **programming language** due to the unanimous desire to learn the language over Android. Please let us know if we are approved for the programming environment change.

Regards,

Jonathan Arceo

As always, let me know what you guys think.

**Comment by dzakich** [comment]
I'll go with the 1st version. 
@jlarceo40 Your comments make sense. I don't feel like there is enough justification to dwell of such technicalities 😺

**Comment by jlarceo40** [comment]
So according to the latest email by the professor, we must have a reason for teaming up together and send it by tomorrow.

Here is my reasoning behind it :)

Title: CPSC 544 - Arceo, Legedza, Pak, SwE (ALPS) Team

Professor Chang-Hyun Jo,

Eric Pak, Stanislav Legedza, and I have decided to group together. Being co-workers within Northrop Grumman's Production Software Engineering Department allows us to equally experience the inadequacies of the department's software development process. It will be interesting to observe that given our similar experience, if we will come to the same conclusion on how we can improve our department's process. 

In addition, we have decided to choose Python as our programming environment due to the unanimous desire to learn the language over Android. Please let us know if we are approved for the programming environment change.

Regards,

Jonathan Arceo

As always, let me know what you guys think.

**Comment by dzakich** [comment]
We should additionally emphasize that we have different but complementary skill set and software development mentality.  For instance,

Stas puts a great emphasis on comprehensive unit-testing, continual refactoring, and error-handling strategies. Jonathan [_something about Jonathan's approach_] while Eric's experience and development mentality dictates [_something about Eric's stuff_]

**Comment by bengk** [comment]
I guess for me..."while Eric's experience and development mentality dictates proper documentation and project management."

**Comment by jlarceo40** [comment]
The email has now been sent and here is the final version:

Title: CPSC 544–51 - Arceo, Legedza, Pak, SwE (ALPS) Team

Professor Chang-Hyun Jo,

Eric Pak, Stanislav Legedza, and I have decided to group together. Eric's experience and development mentality dictates proper documentation and project management. Stas puts a great emphasis on comprehensive unit-testing, continual refactoring, and error-handling strategies. While I put an emphasis on generating a design document prior to coding, designing software to be modular, reusable, modifiable, and putting an honest effort in developing thorough software validation plans. 

In addition, our experience of working for a military contractor allows us to experience similar software development process. It will be interesting to observe that given the commonality, if we will come to the same conclusion as to how the similar processes can be improved.

In addition, we have decided to choose Python as our programming environment due to the unanimous desire to learn the language over Android. Please let us know if we are approved for the programming environment change.

Regards,

**Comment by jlarceo40** [comment]
Once we receive the approval from Prof. Chang-Hyun Jo, this issue can be closed.

**Comment by jlarceo40** [comment]
With the following response from Prof. Chang-Hyun Jo, this issue is now closed:

> Dear Team11 [Jonathan Arceo, Stas Legedza, Eric Pak]:
> 
> Your Group Page
> Team11 [Jonathan Arceo, Stas Legedza, Eric Pak]
> is constructed on Titanium.
> Please check it, and let me know if you find any error.
> Python is approve for your programming environment.
> 
> Thanks.
> Jo
