### ISSUE TITLE
USR01 : 2-8 digit entering

### ISSUE THREAD

**Issue by dzakich** [DLWM-MSE/CPSC-544#8]
USR 01 : As a user, I want to enter 2-8 single digit integers so that the software can sort it into 
increasing order

**Comment by bengk** [comment]
I started work on this.

**Comment by dzakich** [comment]
What are the functional requirements that are associated with this item?

**Comment by bengk** [comment]
Been meaning to ask about that. Should we have the report show which FR/NFR is associated with which User Story?
I have this from my notes:
1a. As a user I want to enter 2-8 single digit integers so that the software can sort it into increasing order.
Must be able to detect non single digit integers in a sequence.
Must be able to detect when user inputs less than 2 or more than 8.
Must be able to detect non integers.
We must be able to detect user enter command so that we know when user is finished.
The algorithm should sort the user input values in increasing order.

**Comment by dzakich** [comment]
Remove "The algorithm should sort the user input values in increasing order" since this is a FR for a different User Story (part of USR08) 
Everything else is spot-on.

**Comment by bengk** [comment]
USR 01: As a user I want to enter 2-8 single digit integers so that the software can sort it into increasing order.

- Must be able to detect non single digit integers in a sequence.

- Must be able to detect when user inputs less than 2 or more than 8.

- Must be able to detect non integers.

- We must be able to detect user enter command so that we know when user is finished.
